### ISSUE TITLE
Application getting 'Killed'

### ISSUE THREAD

**Issue by anishatnitt** [idaholab/malamute#110]
## Bug Description
 Was able to install and run Malamute. All the tests were successful. Whenever I try to run the examples the process starts but eventually fails at some time step

## Steps to Reproduce
Have tried all the examples that come with the package. All of them start and run for a few hours and fail. Have tried with -j 1, -j 2 and the same problem.

## Impact
Have tried in Windows and Linux environment. In both the scenarios its the same result. Config of my Laptop is AMD® Ryzen 5 5600h 6 core, 8GB ram with a dedicated GPU. Tried it on a desktop PC also with config Ryzen 7 3700X 8-Core, 16 GB ram but encountered the same problem.

Looking forward to suggestions from the community. 

Thanks. 

![Screenshot](https://github.com/idaholab/malamute/assets/146836197/147001d7-e10b-437d-b611-5459b34d6846)

**Comment by cticenhour** [comment]
Thanks for submitting your issue! I am moving this to a Discussion post, since this post seems like an individual configuration question. If, after discussing, there is an issue with the code, I can re-open this.
