### ISSUE TITLE
No variable 'ram_spacer_surface_area' found for use in function parser expression | Tutorial given in malamute demonstration

### ISSUE THREAD

**Issue by skvarjun** [idaholab/malamute#167]
## Bug Description
Don't know whether it is a bug!!!

## Steps to Reproduce
I was trying to reproduce the tutorial file given in [https://mooseframework.inl.gov/malamute/demonstration/index.html](https://mooseframework.inl.gov/malamute/demonstration/index.html). I used the same input file given in the tutorial but getting an error as;

`no variable 'ram_spacer_surface_area' found for use in function parser expression`
`no variable 'powder_radius' found for use in function parser expression`
`no variable 'powder_height' found for use in function parser expression`
`no variable 'ram_cc_sinter_punch_height' found for use in function parser expression`

[dcs5_5_mm_constant_properties.zip](https://github.com/user-attachments/files/16989689/dcs5_5_mm_constant_properties.zip)

**Comment by sapitts** [comment]
Hi @skvarjun, 
Thanks for trying out our new tutorial. Unfortunately we can't download zip files; would you please attach the full input file you are using as a text file or as a block comment (with the ``` quotes)?

**Comment by skvarjun** [comment]
`[Variables]
  [temperature]
    initial_condition = 300.0
    block = 'bottom_ram_spacer bottom_cc_spacer bottom_sinter_spacer bottom_punch
             powder top_punch top_sinter_spacer top_cc_spacer top_ram_spacer die_wall'
    order = SECOND
  []
  [potential]
    block = 'bottom_ram_spacer bottom_cc_spacer bottom_sinter_spacer bottom_punch
             powder top_punch top_sinter_spacer top_cc_spacer top_ram_spacer die_wall'
    order = SECOND
  []
  [temperature_bottom_ram_cc_lm]
    block = 'bottom_ram_cc_secondary_subdomain'
    order = SECOND
  []
  [potential_bottom_ram_cc_lm]
    block = 'bottom_ram_cc_secondary_subdomain'
    order = SECOND
  []
  [temperature_bottom_cc_sinter_lm]
    block = 'bottom_cc_sinter_secondary_subdomain'
    order = SECOND
  []
  [potential_bottom_cc_sinter_lm]
    block = 'bottom_cc_sinter_secondary_subdomain'
    order = SECOND
  []
  [temperature_bottom_sinter_punch_lm]
    block = 'bottom_sinter_punch_secondary_subdomain'
    order = SECOND
  []
  [potential_bottom_sinter_punch_lm]
    block = 'bottom_sinter_punch_secondary_subdomain'
    order = SECOND
  []
  [temperature_bottom_punch_powder_lm]
    block = ' bottom_punch_powder_secondary_subdomain'
    order = SECOND
  []
  [potential_bottom_punch_powder_lm]
    block = 'bottom_punch_powder_secondary_subdomain'
    order = SECOND
  []
  [temperature_powder_top_punch_lm]
    block = 'powder_top_punch_secondary_subdomain'
    order = SECOND
  []
  [potential_powder_top_punch_lm]
    block = ' powder_top_punch_secondary_subdomain'
    order = SECOND
  []
  [die_wall_thickness]
    die_wall_thickness = 0.005
  []
  [temperature_top_punch_sinter_lm]
    block = 'top_punch_sinter_secondary_subdomain'
    order = SECOND
  []
  [potential_top_punch_sinter_lm]
    block = 'top_punch_sinter_secondary_subdomain'
    order = SECOND
  []
  [temperature_top_sinter_cc_lm]
    block = 'top_sinter_cc_secondary_subdomain'
    order = SECOND
  []
  [potential_top_sinter_cc_lm]
    block = 'top_sinter_cc_secondary_subdomain'
    order = SECOND
  []
  [temperature_top_cc_ram_lm]
    block = 'top_cc_ram_secondary_subdomain'
    order = SECOND
  []
  [potential_top_cc_ram_lm]
    block = 'top_cc_ram_secondary_subdomain'
    order = SECOND
  []
  [temperature_inside_low_punch_lm]
    block = 'inside_low_punch_secondary_subdomain'
    order = SECOND
  []
  [potential_inside_low_punch_lm]
    block = 'inside_low_punch_secondary_subdomain'
    order = SECOND
  []
  [temperature_inside_powder_lm]
    block = 'inside_powder_secondary_subdomain'
    order = SECOND
  []
  [potential_inside_powder_lm]
    block = 'inside_powder_secondary_subdomain'
    order = SECOND
  []
  [temperature_inside_top_punch_lm]
    block = 'inside_top_punch_secondary_subdomain'
    order = SECOND
  []
  [potential_inside_top_punch_lm]
    block = 'inside_top_punch_secondary_subdomain'
    order = SECOND
  []

  [temperature_gap_top_sinter_die_lm]
    block = 'gap_top_sinter_die_secondary_subdomain'
    order = SECOND
  []
  [temperature_gap_bottom_sinter_die_lm]
    block = 'gap_bottom_sinter_die_secondary_subdomain'
    order = SECOND
  []
[]

[AuxVariables]
  [heat_transfer_radiation]
    order = SECOND
  []

  [electric_field_x]
    family = MONOMIAL #prettier pictures with smoother values
    order = FIRST
    block = 'bottom_ram_spacer bottom_cc_spacer bottom_sinter_spacer bottom_punch
             powder top_punch top_sinter_spacer top_cc_spacer top_ram_spacer die_wall'
  []
  [electric_field_y]
    family = MONOMIAL
    order = FIRST
    block = 'bottom_ram_spacer bottom_cc_spacer bottom_sinter_spacer bottom_punch
             powder top_punch top_sinter_spacer top_cc_spacer top_ram_spacer die_wall'
  []

  [interface_normal_lm]
    order = FIRST
    family = LAGRANGE
    block = 'bottom_ram_cc_secondary_subdomain bottom_cc_sinter_secondary_subdomain
             bottom_sinter_punch_secondary_subdomain bottom_punch_powder_secondary_subdomain
             powder_top_punch_secondary_subdomain top_punch_sinter_secondary_subdomain
             top_sinter_cc_secondary_subdomain top_cc_ram_secondary_subdomain
             inside_low_punch_secondary_subdomain inside_powder_secondary_subdomain
             inside_top_punch_secondary_subdomain'
    initial_condition = 1.0e6
  []
[]

[Kernels]
  [HeatDiff_graphite]
    type = ADHeatConduction
    variable = temperature
    thermal_conductivity = graphite_thermal_conductivity
    extra_vector_tags = 'ref'
    block = 'bottom_ram_spacer bottom_sinter_spacer bottom_punch
             top_punch top_sinter_spacer top_ram_spacer die_wall'
  []
  [HeatTdot_graphite]
    type = ADHeatConductionTimeDerivative
    variable = temperature
    specific_heat = graphite_heat_capacity
    density_name = graphite_density
    extra_vector_tags = 'ref'
    block = 'bottom_ram_spacer bottom_sinter_spacer bottom_punch
             top_punch top_sinter_spacer top_ram_spacer die_wall'
  []
  [electric_graphite]
    type = ADMatDiffusion
    variable = potential
    diffusivity = graphite_electrical_conductivity
    extra_vector_tags = 'ref'
    block = 'bottom_ram_spacer bottom_sinter_spacer bottom_punch
             top_punch top_sinter_spacer top_ram_spacer die_wall'
  []
  [JouleHeating_graphite]
    type = ADJouleHeatingSource
    variable = temperature
    elec = potential
    electrical_conductivity = graphite_electrical_conductivity
    # use_displaced_mesh = true
    extra_vector_tags = 'ref'
    block = 'bottom_ram_spacer bottom_sinter_spacer bottom_punch
             top_punch top_sinter_spacer top_ram_spacer die_wall'
  []

  [HeatDiff_anistropic_carbon_fiber]
    type = ADMatAnisoDiffusion
    diffusivity = ccfiber_aniso_thermal_conductivity
    variable = temperature
    extra_vector_tags = 'ref'
    block = 'bottom_cc_spacer top_cc_spacer'
  []
  [HeatTdot_carbon_fiber]
    type = ADHeatConductionTimeDerivative
    variable = temperature
    specific_heat = ccfiber_heat_capacity
    density_name = ccfiber_density
    extra_vector_tags = 'ref'
    block = 'bottom_cc_spacer top_cc_spacer'
  []
  [electric_carbon_fiber]
    type = ADMatDiffusion
    variable = potential
    diffusivity = ccfiber_electrical_conductivity
    extra_vector_tags = 'ref'
    block = 'bottom_cc_spacer top_cc_spacer'
  []
  [JouleHeating_carbon_fiber]
    type = ADJouleHeatingSource
    variable = temperature
    elec = potential
    electrical_conductivity = ccfiber_electrical_conductivity
    # use_displaced_mesh = true
    extra_vector_tags = 'ref'
    block = 'bottom_cc_spacer top_cc_spacer'
  []

  [HeatDiff_powder]
    type = ADHeatConduction
    variable = temperature
    thermal_conductivity = copper_thermal_conductivity
    extra_vector_tags = 'ref'
    block = 'powder'
  []
  [HeatTdot_powder]
    type = ADHeatConductionTimeDerivative
    variable = temperature
    specific_heat = copper_heat_capacity
    density_name = copper_density
    extra_vector_tags = 'ref'
    block = 'powder'
  []
  [electric_powder]
    type = ADMatDiffusion
    variable = potential
    diffusivity = copper_electrical_conductivity
    extra_vector_tags = 'ref'
    block = 'powder'
  []
  [JouleHeating_powder]
    type = ADJouleHeatingSource
    variable = temperature
    elec = potential
    electrical_conductivity = copper_electrical_conductivity
    # use_displaced_mesh = true
    extra_vector_tags = 'ref'
    block = 'powder'
  []
[]

[AuxKernels]
  [heat_transfer_radiation]
    type = ParsedAux
    variable = heat_transfer_radiation
    boundary = 'bottom_ram_spacer_right bottom_ram_spacer_overhang_right bottom_cc_spacer_right
                bottom_sinter_spacer_right bottom_sinter_spacer_overhang_right uncovered_bottom_punch_right
                top_sinter_spacer_overhang_right top_sinter_spacer_right die_wall_right uncovered_top_punch_right
                top_cc_spacer_right top_ram_spacer_overhang_right top_ram_spacer_right'
    coupled_variables = 'temperature'
    constant_names = 'boltzmann epsilon temperature_farfield' #published emissivity for graphite is 0.85
    constant_expressions = '5.67e-8 0.85 300.0' #roughly room temperature, which is probably too cold
    expression = '-boltzmann*epsilon*(temperature^4-temperature_farfield^4)'
  []

  [electrostatic_calculation_x]
    type = PotentialToFieldAux
    gradient_variable = potential
    variable = electric_field_x
    sign = negative
    component = x
    block = 'bottom_ram_spacer bottom_cc_spacer bottom_sinter_spacer bottom_punch
             powder top_punch top_sinter_spacer top_cc_spacer top_ram_spacer die_wall'
  []
  [electrostatic_calculation_y]
    type = PotentialToFieldAux
    gradient_variable = potential
    variable = electric_field_y
    sign = negative
    component = y
    block = 'bottom_ram_spacer bottom_cc_spacer bottom_sinter_spacer bottom_punch
             powder top_punch top_sinter_spacer top_cc_spacer top_ram_spacer die_wall'
  []
[]

[Functions]
  [current_application]
    type = PiecewiseLinear
    x = '0            40                                    60                                   160                                   200                                   230                                   340                                   850                                   890                                   900                                   950                                   1010                                  1050                                  1100                                  1200                                  1240                                1250                        1260 1800'
    y = '0  ${fparse 561/ram_spacer_surface_area} ${fparse 502/ram_spacer_surface_area} ${fparse 500/ram_spacer_surface_area} ${fparse 417/ram_spacer_surface_area} ${fparse 417/ram_spacer_surface_area} ${fparse 566/ram_spacer_surface_area} ${fparse 952/ram_spacer_surface_area} ${fparse 926/ram_spacer_surface_area} ${fparse 926/ram_spacer_surface_area} ${fparse 977/ram_spacer_surface_area}  ${fparse 902/ram_spacer_surface_area} ${fparse 902/ram_spacer_surface_area} ${fparse 927/ram_spacer_surface_area} ${fparse 926/ram_spacer_surface_area} ${fparse 903/ram_spacer_surface_area} ${fparse 4/ram_spacer_surface_area}  0    0'
    scale_factor = 1.0
  []
[]

[BCs]
  [temperature_rams]
    type = ADDirichletBC
    variable = temperature
    value = 300.0
    boundary = 'top_ram_spacer_top bottom_ram_spacer_bottom'
  []
  [external_surface_temperature]
    type = CoupledVarNeumannBC
    variable = temperature
    v = heat_transfer_radiation
    boundary = 'bottom_ram_spacer_right bottom_ram_spacer_overhang_right bottom_cc_spacer_right
                bottom_sinter_spacer_right bottom_sinter_spacer_overhang_right uncovered_bottom_punch_right
                top_sinter_spacer_overhang_right top_sinter_spacer_right die_wall_right uncovered_top_punch_right
                top_cc_spacer_right top_ram_spacer_overhang_right top_ram_spacer_right'
  []
  [electric_top]
    type = ADFunctionNeumannBC
    variable = potential
    function = 'current_application'
    boundary = 'top_ram_spacer_top'
  []
  [electric_bottom]
    type = ADDirichletBC
    variable = potential
    value = 0.0
    boundary = 'bottom_ram_spacer_bottom'
  []
[]

[Constraints]
  [thermal_contact_interface_low_ram_cc_spacers]
    type = ModularGapConductanceConstraint
    variable = temperature_bottom_ram_cc_lm
    secondary_variable = temperature
    primary_boundary = bottom_ram_spacer_top
    primary_subdomain = bottom_ram_cc_primary_subdomain
    secondary_boundary = bottom_cc_spacer_bottom
    secondary_subdomain = bottom_ram_cc_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_thermal_interface_bottom_ram_cc'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_ram_cc_low_spacers]
    type = ModularGapConductanceConstraint
    variable = potential_bottom_ram_cc_lm
    secondary_variable = potential
    primary_boundary = bottom_ram_spacer_top
    primary_subdomain = bottom_ram_cc_primary_subdomain
    secondary_boundary = bottom_cc_spacer_bottom
    secondary_subdomain = bottom_ram_cc_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_electric_interface_bottom_ram_cc'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_cc_sinter_low_spacers]
    type = ModularGapConductanceConstraint
    variable = temperature_bottom_cc_sinter_lm
    secondary_variable = temperature
    primary_boundary = bottom_cc_spacer_top
    primary_subdomain = bottom_cc_sinter_primary_subdomain
    secondary_boundary = bottom_sinter_spacer_bottom
    secondary_subdomain = bottom_cc_sinter_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_thermal_interface_bottom_cc_sinter'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_cc_sinter_low_spacers]
    type = ModularGapConductanceConstraint
    variable = potential_bottom_cc_sinter_lm
    secondary_variable = potential
    primary_boundary = bottom_cc_spacer_top
    primary_subdomain = bottom_cc_sinter_primary_subdomain
    secondary_boundary = bottom_sinter_spacer_bottom
    secondary_subdomain = bottom_cc_sinter_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_electric_interface_bottom_cc_sinter'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_low_sinter_punch]
    type = ModularGapConductanceConstraint
    variable = temperature_bottom_sinter_punch_lm
    secondary_variable = temperature
    primary_boundary = bottom_sinter_spacer_top
    primary_subdomain = bottom_sinter_punch_primary_subdomain
    secondary_boundary = bottom_punch_bottom
    secondary_subdomain = bottom_sinter_punch_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_thermal_interface_bottom_sinter_punch'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_low_sinter_punch]
    type = ModularGapConductanceConstraint
    variable = potential_bottom_sinter_punch_lm
    secondary_variable = potential
    primary_boundary = bottom_sinter_spacer_top
    primary_subdomain = bottom_sinter_punch_primary_subdomain
    secondary_boundary = bottom_punch_bottom
    secondary_subdomain = bottom_sinter_punch_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_electric_interface_bottom_sinter_punch'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_low_punch_powder]
    type = ModularGapConductanceConstraint
    variable = temperature_bottom_punch_powder_lm
    secondary_variable = temperature
    primary_boundary = bottom_punch_top
    primary_subdomain = bottom_punch_powder_primary_subdomain
    secondary_boundary = powder_bottom
    secondary_subdomain = bottom_punch_powder_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_thermal_interface_bottom_punch_powder'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_low_punch_powder]
    type = ModularGapConductanceConstraint
    variable = potential_bottom_punch_powder_lm
    secondary_variable = potential
    primary_boundary = bottom_punch_top
    primary_subdomain = bottom_punch_powder_primary_subdomain
    secondary_boundary = powder_bottom
    secondary_subdomain = bottom_punch_powder_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_electric_interface_bottom_punch_powder'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_powder_top_punch]
    type = ModularGapConductanceConstraint
    variable = temperature_powder_top_punch_lm
    secondary_variable = temperature
    primary_boundary = powder_top
    primary_subdomain = powder_top_punch_primary_subdomain
    secondary_boundary = top_punch_bottom
    secondary_subdomain = powder_top_punch_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_thermal_interface_powder_top_punch'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_powder_top_punch]
    type = ModularGapConductanceConstraint
    variable = potential_powder_top_punch_lm
    secondary_variable = potential
    primary_boundary = powder_top
    primary_subdomain = powder_top_punch_primary_subdomain
    secondary_boundary = top_punch_bottom
    secondary_subdomain = powder_top_punch_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_electric_interface_powder_top_punch'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_top_punch_sinter]
    type = ModularGapConductanceConstraint
    variable = temperature_top_punch_sinter_lm
    secondary_variable = temperature
    primary_boundary = top_punch_top
    primary_subdomain = top_punch_sinter_primary_subdomain
    secondary_boundary = top_sinter_spacer_bottom
    secondary_subdomain = top_punch_sinter_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_thermal_interface_top_punch_sinter'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_top_punch_sinter]
    type = ModularGapConductanceConstraint
    variable = potential_top_punch_sinter_lm
    secondary_variable = potential
    primary_boundary = top_punch_top
    primary_subdomain = top_punch_sinter_primary_subdomain
    secondary_boundary = top_sinter_spacer_bottom
    secondary_subdomain = top_punch_sinter_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_electric_interface_top_punch_sinter'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_top_sinter_cc_spacers]
    type = ModularGapConductanceConstraint
    variable = temperature_top_sinter_cc_lm
    secondary_variable = temperature
    primary_boundary = top_sinter_spacer_top
    primary_subdomain = top_sinter_cc_primary_subdomain
    secondary_boundary = top_cc_spacer_bottom
    secondary_subdomain = top_sinter_cc_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_thermal_interface_top_sinter_cc_spacer'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_top_sinter_cc_spacers]
    type = ModularGapConductanceConstraint
    variable = potential_top_sinter_cc_lm
    secondary_variable = potential
    primary_boundary = top_sinter_spacer_top
    primary_subdomain = top_sinter_cc_primary_subdomain
    secondary_boundary = top_cc_spacer_bottom
    secondary_subdomain = top_sinter_cc_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_electric_interface_top_sinter_cc_spacer'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_top_cc_ram_spacers]
    type = ModularGapConductanceConstraint
    variable = temperature_top_cc_ram_lm
    secondary_variable = temperature
    primary_boundary = top_cc_spacer_top
    primary_subdomain = top_cc_ram_primary_subdomain
    secondary_boundary = top_ram_spacer_bottom
    secondary_subdomain = top_cc_ram_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_thermal_interface_top_cc_ram_spacer'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_top_cc_ram_spacers]
    type = ModularGapConductanceConstraint
    variable = potential_top_cc_ram_lm
    secondary_variable = potential
    primary_boundary = top_cc_spacer_top
    primary_subdomain = top_cc_ram_primary_subdomain
    secondary_boundary = top_ram_spacer_bottom
    secondary_subdomain = top_cc_ram_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'closed_electric_interface_top_cc_ram_spacer'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_inside_die_low_punch]
    type = ModularGapConductanceConstraint
    variable = temperature_inside_low_punch_lm
    secondary_variable = temperature
    primary_boundary = die_wall_left
    primary_subdomain = inside_die_primary_subdomain
    secondary_boundary = bottom_punch_right
    secondary_subdomain = inside_low_punch_secondary_subdomain
    gap_geometry_type = CYLINDER
    gap_flux_models = 'thermal_conduction_wall_low_punch closed_thermal_interface_inside_die_low_punch'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_inside_die_low_punch]
    type = ModularGapConductanceConstraint
    variable = potential_inside_low_punch_lm
    secondary_variable = potential
    primary_boundary = die_wall_left
    primary_subdomain = inside_die_primary_subdomain
    secondary_boundary = bottom_punch_right
    secondary_subdomain = inside_low_punch_secondary_subdomain
    gap_geometry_type = CYLINDER
    gap_flux_models = 'electrical_conduction_wall_low_punch closed_electric_interface_inside_die_low_punch'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_inside_die_powder]
    type = ModularGapConductanceConstraint
    variable = temperature_inside_powder_lm
    secondary_variable = temperature
    primary_boundary = die_wall_left
    primary_subdomain = inside_die_primary_subdomain
    secondary_boundary = powder_right
    secondary_subdomain = inside_powder_secondary_subdomain
    gap_geometry_type = CYLINDER
    gap_flux_models = 'thermal_conduction_wall_powder closed_thermal_interface_inside_die_powder'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_inside_die_powder]
    type = ModularGapConductanceConstraint
    variable = potential_inside_powder_lm
    secondary_variable = potential
    primary_boundary = die_wall_left
    primary_subdomain = inside_die_primary_subdomain
    secondary_boundary = powder_right
    secondary_subdomain = inside_powder_secondary_subdomain
    gap_geometry_type = CYLINDER
    gap_flux_models = 'electrical_conduction_wall_powder closed_electric_interface_inside_die_powder'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_contact_interface_inside_die_top_punch]
    type = ModularGapConductanceConstraint
    variable = temperature_inside_top_punch_lm
    secondary_variable = temperature
    primary_boundary = die_wall_left
    primary_subdomain = inside_die_primary_subdomain
    secondary_boundary = top_punch_right
    secondary_subdomain = inside_top_punch_secondary_subdomain
    gap_geometry_type = CYLINDER
    gap_flux_models = 'thermal_conduction_wall_top_punch closed_thermal_interface_inside_die_top_punch'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [electrical_contact_interface_inside_die_top_punch]
    type = ModularGapConductanceConstraint
    variable = potential_inside_top_punch_lm
    secondary_variable = potential
    primary_boundary = die_wall_left
    primary_subdomain = inside_die_primary_subdomain
    secondary_boundary = top_punch_right
    secondary_subdomain = inside_top_punch_secondary_subdomain
    gap_geometry_type = CYLINDER
    gap_flux_models = 'electrical_conduction_wall_top_punch closed_electric_interface_inside_die_top_punch'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []

  [thermal_gap_contact_interface_bottom_sinter_die]
    type = ModularGapConductanceConstraint
    variable = temperature_gap_bottom_sinter_die_lm
    secondary_variable = temperature
    primary_boundary = bottom_sinter_spacer_overhang_top
    primary_subdomain = gap_bottom_sinter_die_primary_subdomain
    secondary_boundary = die_wall_bottom
    secondary_subdomain = gap_bottom_sinter_die_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'gap_thermal_interface_bottom_sinter_die'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
  [thermal_gap_contact_interface_top_sinter_die]
    type = ModularGapConductanceConstraint
    variable = temperature_gap_top_sinter_die_lm
    secondary_variable = temperature
    primary_boundary = top_sinter_spacer_overhang_bottom
    primary_subdomain = gap_top_sinter_die_primary_subdomain
    secondary_boundary = die_wall_top
    secondary_subdomain = gap_top_sinter_die_secondary_subdomain
    gap_geometry_type = PLATE
    gap_flux_models = 'gap_thermal_interface_top_sinter_die'
    extra_vector_tags = 'ref'
    correct_edge_dropping = true
    # use_displaced_mesh = true
  []
[]

[Materials]
  [carbon_fiber_electro_thermal_properties]
    type = ADGenericConstantMaterial
    prop_names = 'ccfiber_density ccfiber_thermal_conductivity ccfiber_heat_capacity ccfiber_electrical_conductivity ccfiber_hardness'
    prop_values = ' 1.5e3                 5.0                     1.25e3                   4.0e4                           1.0'
    block = 'bottom_cc_spacer top_cc_spacer bottom_ram_cc_secondary_subdomain top_sinter_cc_secondary_subdomain'
    # density (kg/m^3) and electrical conductivity (S/m) from Schunk CF226 manufacturer's datasheet, available at http://schunk-tokai.pl/en/wp-content/uploads/e_CF-226.pdf
    # thermal conductivity (W/m-K), perpendicular to fiber direction, from Schunk CF226 manufacturer's datasheet, available at http://schunk-tokai.pl/en/wp-content/uploads/e_CF-226.pdf
    # specific heat capacity (J/kg-K) from Sommers et al. App. Thermal Engineering 30(11-12) (2010) 1277-1291 for Schunk FU2952
    # hardness set to unity to remove dependence on that quantity
  []
[]

[Postprocessors]
  [applied_current]
    type = FunctionValuePostprocessor
    function = current_application
  []

  [pyrometer_point]
    type = PointValue
    variable = temperature
    point = '${fparse powder_radius + 0.004} ${fparse ram_cc_sinter_punch_height + powder_height / 2.0} 0'
  []
[]

[Outputs]
  color = false
  csv = true
  exodus = true
  perf_graph = true
[]`

**Comment by sapitts** [comment]
Is this the full input file? If yes, how did you assemble it / where did you find this version?

I'm trying to understand your process better so that I can determine which correction to implement in the tutorial. Thanks!

**Comment by skvarjun** [comment]
I took it from the INL repository - see the link [https://mooseframework.inl.gov/malamute/demonstration/index.html](https://mooseframework.inl.gov/malamute/demonstration/index.html).

I am also new to the Malamute framework, and any advise would be helpful.

**Comment by sapitts** [comment]
Try this input file, which is stored directly in our code repository and tested daily against the current version of MALAMUTE: https://github.com/idaholab/malamute/blob/devel/tutorials/efas/introduction/dcs5_copper_constant_properties_electrothermal.i

**Comment by skvarjun** [comment]
Thank you. It is running in a cluster. I also wonder if there is any parallelization scheme for Malamute using MPI or any other packages, especially running in an HPC cluster.

**Comment by sapitts** [comment]
Good! I'll change this issue to a feature request and add a direct link in the tutorial to the complete input file from the repository based on your feed back here

**Comment by sapitts** [comment]
To run in parallel, see the link in the second bullet point under 'Simulations': https://mooseframework.inl.gov/help/faq/index.html

You may also find it useful to work through the MOOSE tutorials that are relevant to you: https://mooseframework.inl.gov/getting_started/examples_and_tutorials/index.html

**Comment by skvarjun** [comment]
Thank you. I appreciate your help.
