### ISSUE TITLE
Dr. Sinter specific input files and mesh

### ISSUE THREAD

**Issue by moosebuild** [idaholab/malamute#20]
In [GitLab](https://hpcgitlab.hpc.inl.gov/idaholab/malamute/-/issues/20) by @cticenhour on Dec 14, 2021, 16:01

This issue is a reproduction of the archived freya#21 for SQA purposes. Please refer to that issue for any extended discussion that may exist beyond this description. 

## Reason
Validation comparisons of the Freya code require geometry and input files that align with the specifics of the CAES Dr. Sinter machine.

## Design
Add mesh script, mesh, and corresponding input files

## Impact
Will add capability to run engineering scale simulations for direct comparison with the CAES Dr. Sinter machine

**Comment by moosebuild** [comment]
In GitLab by @sapitts on Jul 14, 2022, 16:13

mentioned in commit 268e2eee14e66094b5e6d7a670afd5e82d6f354c

**Comment by moosebuild** [comment]
In GitLab by @cticenhour on Jul 14, 2022, 16:13

mentioned in commit e06afb4d211d105e90150f21a574b75dbeccfd23

**Comment by moosebuild** [comment]
In GitLab by @cticenhour on Jul 14, 2022, 16:13

mentioned in commit 6058abceff9779811e3fd559e3fc31277af9059a

**Comment by moosebuild** [comment]
In GitLab by @cticenhour on Jul 14, 2022, 16:13

mentioned in commit 508e260f41256b9a0cfdc6853822c37adaa71f89

**Comment by moosebuild** [comment]
In GitLab by @cticenhour on Jul 14, 2022, 16:13

mentioned in commit a7011e59be5aa2c75b52f256eedcb0ae54c208a4

**Comment by sapitts** [comment]
The CAES Dr. Sinter machine is no longer used for EFAS simulation calibration and validation efforts; these efforts have been replaced by efforts using the newer and more thoroughly instrumented DCS-5 machine, see #91
