### ISSUE TITLE
New moosebuild will break tests

### ISSUE THREAD

**Issue by moosebuild** [idaholab/malamute#29]
In [GitLab](https://hpcgitlab.hpc.inl.gov/idaholab/malamute/-/issues/29) by @cticenhour on Feb 22, 2022, 11:37

## Bug Description
"New moosebuild" will break tests on CIVET due to OS, gcc, and mpich changes. Any failing tests should be fixed up before that changeover finishes. 

The current failing tests are exodiffs: 

- `test:melt_pool_fluid.fluid`
- `test:gradient_regularization.gradient_regularization`

New formerly freya tests being added in !5 had one failure due to a convergence issue:

- `test:bcs/radiation_heat_loss.simple_radiation`

## Steps to Reproduce
Open a terminal and perform the following:

```
% ssh rod.hpc.inl.gov
% new_moosebuild
% module load moose-libmesh-vtk python
% <clone current malamute>
% <build malamute>
% ./run_tests -j8
```

## Impact
MALAMUTE will stop updating if this isn't fixed.

**Comment by moosebuild** [comment]
In GitLab by @cticenhour on Jul 14, 2022, 16:13

mentioned in commit a2937552572a8c0cb1a331c03b4b442ff6f92a1c

**Comment by cticenhour** [comment]
This is an old issue from earlier changes to CIVET recipes. [MALAMUTE is currently green](https://civet.inl.gov/event/124650/), so this should be closed.
